### ISSUE TITLE
Is this API active?

### ISSUE THREAD

**Issue by bkkrishna** [ernilambar/esewa-payment-gateway-implementation#1]
I was wondering if the author has still maintained this as an active repo or API. If it is, then I would like to request for its proper implementation guide in Nepali e-commerce applications, probably for Laravel 5.1.

Thanks in advance.

**Comment by ernilambar** [comment]
Hello,

Thanks for showing interest on the implementation. This is the basic implementation of eSewa in PHP. There is not even IPN implementation. If you want to try it out in Laravel, you can checkout the PDF documentation for the detail. That PDF is 2 years old. May be API is updated now. You can contact eSewa to confirm whether API is updated or not.

Thanks
